version: "3"
services:
  web:
    container_name: web
    build:
      context: ./frontend
      dockerfile: ../docker/web/Dockerfile
    ports:
      - "3000:3000"
    networks:
      - app_network
    volumes:
      - ./:/frontend
    command: sh -c 'cd /frontend && npm start'
    depends_on:
      - api
  api:
    container_name: api
    build:
      context: ./backend
      dockerfile: ../docker/api/Dockerfile
    ports:
      - "8080:8080"
    networks:
      - app_network
    depends_on:
      - db
  db:
    container_name: postgres
    build: docker/db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "test_db"
    networks:
      - app_network

volumes:
  db_data:

networks:
  app_network:
    driver: bridge
